### PR TITLE
Center modal and fix scrolling

### PR DESCRIPTION
**Pull request by caesar2164**
@stvstnfrd - styling change for sga modal

### CODE REVIEW

**Comment by stvstnfrd** [comment]
@caesar2164 Do we still want/need this?

**Comment by caesar2164** [comment]
This is a question for @Stanford-Online/openedx-courseops

**Comment by stvstnfrd** [comment]
Can you provide some context on this @caesar2164 ?

**Comment by stvstnfrd** [comment]
@caesar2164 Do you mind demoing this change for Nathaniel?

If he's +1, let's merge it.

**Comment by stvstnfrd** [comment]
+1 reluctantly ;)

**Pull request merged**
