### PR TITLE
Add Mobile Support

### PR DESCRIPTION
**Pull request by libremente**
Added mobile decorator.
Corrected a typo in the README file.

@stvstnfrd @caesar2164

### CODE REVIEW

**Comment by caesar2164** [comment]
looks good to me: 👍

**Comment by stvstnfrd** [comment]
+1

**Comment by stvstnfrd** [comment]
@caesar2164 Are we running a custom copy of sga currently?
If not, let's close this?

**Comment by caesar2164** [comment]
@stv, we are currently mirroring edX for this xblock. Should I lob this PR to the parent xblock?

**Comment by stvstnfrd** [comment]
Eh, my first thought is we may as well lob it to them, since it's already written.

But it's not clear to me how well they support it (first introduced here [1], more details here [2]),
but their response will be a good indicator.
The only XModule that supports it is the HTML module.
I didn't scan all XBlocks, but at least ORA2 does _not_ support it either.

And since you personally haven't tested this on mobile, I'm hesitant for you to PR it upstream, since you can't vouch for its performance.

Given that, I'm inclined to say "let's forget this; if edx wants mobile support for their XBlock; they can add it when they test it."

[1] https://github.com/edx/edx-platform/pull/8888
[2] https://openedx.atlassian.net/wiki/spaces/EDUCATOR/pages/29688043/Course+Blocks+API#CourseBlocksAPI-BlockRendering:Web,Responsive,andNative

**Comment by stvstnfrd** [comment]
@caesar2164 Also, remember it's @stvstnfrd; `stv` is someone else ;)

**Pull request closed without merging**
